### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by TilenHumar** [TilenHumar/APPR-2021-22#1]
Pozdravljeni,

sporočam, da bi projekt rad oddal v ocenjevanje.

Lep pozdrav,
Tilen Humar

**Comment by katarinabrilej** [comment]
Hvala, sporočim, ko bo ocenjen.

Lep pozdrav,
Katarina

**Comment by katarinabrilej** [comment]
Sem vpisala oceno v spletno učilnico. Pri vizualizaciji dobiš še dodatni dve točki, da tako da je skupna ocena 10.

Lep pozdrav,
Katarina

**Comment by TilenHumar** [comment]
Hvala!
